### PR TITLE
remove auto padding in decryptData.js "fixes #1"

### LINKED ISSUE #1: digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
Hi,
I'm getting this error while using lpass.getAccounts. I'm not expert in node js but I don't understand why I get this error. The functions I used are :

``` javascript
lpass.loadVault(USERNAME, PASSWORD);
lpass.getVault();
lpass.getAccounts(
      USERNAME,
      PASSWORD,
      SEARCH
    );
```

With SEARCH = undefined;
I take your index.js example and comment out functions I don't need.
Can you tell me if I missed something?
Thank you

### PR DESCRIPTION
**Pull request by AndreiSoroka**

### CODE REVIEW

**Comment by dfrankland** [comment]
Wow nice! I'll merge, test, and publish ASAP. Thank you 👍

**Comment by AndreiSoroka** [comment]
It's cool! Thx!

**Comment by AndreiSoroka** [comment]
@dfrankland, I'm not sure...
Maybe if use 'aes-256-cbc' then auto padding is need.
Need testing. 
Say me plz, if you up version in npm

**Comment by dfrankland** [comment]
I've tested with my personal account and it works great 👍 I've now published as `lastpass@1.0.3`.

**Pull request merged**
